general:
  Version : 1
  Geometry : $BURSTCUBE/Simulation/MEGAlib/test/BurstCube_1Cylinder.geo.setup
  CheckForOverlaps : 1000 0.01
  PhysicsListEM : Livermore
  StoreCalibrate : true
  StoreSimulationInfo : true
  StoreOnlyEventsWithEnergyLoss : true 
  DiscretizeHits : true

source:
  name : FFPS
  NTriggers : 1000
  Flux : 1000.0
  ParticleType : 1
  Beam : FarfieldPointSource
  
run:
  basename : test
  srcdir : $BURSTCUBE/Simulation/MEGAlib/test/
  simdir : $BURSTCUBE/Simulation/MEGAlib/test/
  emin : 100.000
  emax : 300.000
  enumbins : 3
  costhetamin : 0.5
  costhetamax : 1.0 
  costhetanumbins : 3



